package com.taskmanagement.model;

import java.time.LocalDate;

/**
 * Model class representing a single task.
 * Demonstrates ENCAPSULATION: all fields are private and accessed via getters/setters.
 */
public class Task {

    // Allowed values (used by the GUI combo boxes and validation)
    public static final String[] PRIORITIES = {"LOW", "MEDIUM", "HIGH"};
    public static final String[] STATUSES = {"PENDING", "IN PROGRESS", "COMPLETED"};

    private int id;
    private String title;
    private String description;
    private LocalDate dueDate;
    private String priority;
    private String status;

    /** Default constructor. */
    public Task() {
    }

    /** Constructor for a new task (id is generated by the database). */
    public Task(String title, String description, LocalDate dueDate, String priority, String status) {
        this.title = title;
        this.description = description;
        this.dueDate = dueDate;
        this.priority = priority;
        this.status = status;
    }

    /** Constructor for an existing task loaded from the database. */
    public Task(int id, String title, String description, LocalDate dueDate, String priority, String status) {
        this(title, description, dueDate, priority, status);
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "Task{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", dueDate=" + dueDate +
                ", priority='" + priority + '\'' +
                ", status='" + status + '\'' +
                '}';
    }
}
